# RatiChat AI - Full-Stack Containerized Architecture

services:
  postgres:
    image: postgres:14-alpine
    container_name: ratichat_postgres
    environment:
      POSTGRES_USER: ratichat
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ratichat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ratichat_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ratichat"]
      interval: 30s
      timeout: 10s
      retries: 5

  ratichat_backend:
    build:
      context: .
      dockerfile: Dockerfile  # Use main Dockerfile for production-ready build
    container_name: ratichat_backend
    ports:
      - "8000:8000" # Expose the API server
    volumes:
      - ./data:/app/data # Persist ratichat data (db, context storage, etc.)
      - ./matrix_store:/app/matrix_store # Persist matrix session data
      - ./.env:/app/.env:ro # Mount .env file for configuration (read-only)
    depends_on:
      postgres:
        condition: service_healthy
      # Note: Storage service (arweave-service or s3-service) dependency is handled by profiles
      # Use: docker-compose --profile arweave up  OR  docker-compose --profile s3 up
    networks:
      - ratichat_network
    env_file:
      - .env # Load environment variables from .env file
    environment:
      # Additional runtime environment
      - PYTHONUNBUFFERED=1
      - RATICHAT_DB_PATH=/app/data/ratichat.db
      - ARWEAVE_INTERNAL_UPLOADER_SERVICE_URL=http://arweave-service:8001
      # S3 Storage Configuration (use environment variables from .env)
      # S3_API_KEY, S3_API_ENDPOINT, CLOUDFRONT_DOMAIN will be loaded from .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  arweave-service:
    build:
      context: ./arweave-service
      dockerfile: Dockerfile
    container_name: arweave_service
    ports:
      - "8001:8001"  # Expose for testing and direct access
    environment:
      - ARWEAVE_WALLET_PATH=/data/arweave_wallet.json
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount the wallet file directly from host data directory
      - ./data/arweave_wallet.json:/data/arweave_wallet.json:ro
    networks:
      - ratichat_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8001/health')\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - arweave  # Only start when 'arweave' profile is specified

  s3-service:
    build:
      context: ./s3-service
      dockerfile: Dockerfile
    container_name: s3_service
    ports:
      - "8001:8001"  # Same port as arweave-service (use one or the other)
    environment:
      - S3_API_KEY=${S3_API_KEY}
      - S3_API_ENDPOINT=${S3_API_ENDPOINT}
      - CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}
      - S3_SERVICE_API_KEY=${S3_SERVICE_API_KEY:-}
      - PYTHONUNBUFFERED=1
    networks:
      - ratichat_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8001/health')\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - s3  # Only start when 's3' profile is specified

  ratichat_ui:
    build:
      context: ./ui-nextjs # Point to the Next.js app
      dockerfile: Dockerfile
    container_name: ratichat_ui
    ports:
      - "3000:3000"
    networks:
      - ratichat_network
    environment:
      # For client-side API calls (from browser)
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      # For server-side API calls (from Next.js server)
      - INTERNAL_API_URL=http://ratichat_backend:8000
    depends_on:
      - ratichat_backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ratichat_network:
    driver: bridge
