name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  push:
    branches: [develop]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry self add poetry-plugin-export
      - name: Generate requirements.txt from Poetry
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -v --junitxml=pytest.xml
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest.xml
